spring.application.name=rabbit-service

spring.datasource.url=jdbc:mysql://localhost:3306/desarrollowebii
spring.datasource.username=root
spring.datasource.password=seronoser


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


app.queue.name=log-queue

app.queue.name.2=otra-queue