spring.application.name=auditoria-service

spring.datasource.url=jdbc:mysql://localhost:3306/mundomuebles
spring.datasource.username=root
spring.datasource.password=root

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.queue.name=auditoria-queue